// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyATnyiPqKzF7cpJNDMm8vf1OJU5CK7XKbs',
    appId: '1:738196084623:web:fa3f6d15185ca01d5cddfa',
    messagingSenderId: '738196084623',
    projectId: 'studentinfo-80d5f',
    authDomain: 'studentinfo-80d5f.firebaseapp.com',
    storageBucket: 'studentinfo-80d5f.firebasestorage.app',
    measurementId: 'G-5T243EKR5F',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6c5lNm9IT5Tlv7koTgpWacR7RhO2kFUI',
    appId: '1:738196084623:android:fb2a422de100623c5cddfa',
    messagingSenderId: '738196084623',
    projectId: 'studentinfo-80d5f',
    storageBucket: 'studentinfo-80d5f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB16d24y8T6oJX0HurI_1PoQ9EYETHUlD4',
    appId: '1:738196084623:ios:3439d70057ad8fc75cddfa',
    messagingSenderId: '738196084623',
    projectId: 'studentinfo-80d5f',
    storageBucket: 'studentinfo-80d5f.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasics',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB16d24y8T6oJX0HurI_1PoQ9EYETHUlD4',
    appId: '1:738196084623:ios:3439d70057ad8fc75cddfa',
    messagingSenderId: '738196084623',
    projectId: 'studentinfo-80d5f',
    storageBucket: 'studentinfo-80d5f.firebasestorage.app',
    iosBundleId: 'com.example.flutterBasics',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyATnyiPqKzF7cpJNDMm8vf1OJU5CK7XKbs',
    appId: '1:738196084623:web:6517e9d1272b878a5cddfa',
    messagingSenderId: '738196084623',
    projectId: 'studentinfo-80d5f',
    authDomain: 'studentinfo-80d5f.firebaseapp.com',
    storageBucket: 'studentinfo-80d5f.firebasestorage.app',
    measurementId: 'G-2GHK3TG1EV',
  );
}
